# Generated by Django 4.0.1 on 2022-01-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='edad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(max_length=20, verbose_name='Nacionalidad'),
        ),
    ]
