# Generated by Django 4.0.1 on 2022-01-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0003_autor_seudonimo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
    ]
