# Generated by Django 4.0.1 on 2022-01-17 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0002_alter_prestamo_libro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lector',
            options={'verbose_name': 'Lector'},
        ),
    ]
