# Generated by Django 4.0.1 on 2022-01-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0003_alter_lector_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lector',
            options={'verbose_name': 'Lector', 'verbose_name_plural': 'Lectores'},
        ),
    ]
