# Generated by Django 4.0.1 on 2022-01-17 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_alter_libro_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
